### ISSUE TITLE
Using vrops-export with AD user

### ISSUE THREAD

**Issue by ilker-aktuna** [vmware/vrops-export#21]
I am trying to use vrops-export with my AD user instead of a local user.
Is it supported ? if it is supported how can I select this login method ?
if not, can it be supported ?

**Comment by prydin** [comment]
Sorry for the late reply. Yes, AD authentication is supported. The thing that confuses some people is that you need to refer to the name of the Authentication Source rather than the AD domain. Ibn my lab, I have a authentication source called "Pontus AD", so if I want to log in as "pontus" on that authentication source, I type this command:

```exporttool.sh -u "pontus@Pontus AD" -p secret -d samples/simple.yaml -H https://myhost```

**Comment by wavecentral** [comment]
Also, if your AD implementation requires a FQDN user like first.last@company.com and you have an authentication source in the UI as 'COMPANY', you could do:

`exporttool.bat -u "COMPANY\first.last@company.com" -p secret -d samples/simple.yaml -H https://myhost.company.com`
